repos:
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.2
    hooks:
      - id: flake8
        name: Style Guide Enforcement (flake8)
        args:
          - '--max-line-length=120'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.660
    hooks:
      - id: mypy
        name: Optional Static Typing for Python (mypy)
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v2.4.3
    hooks:
      - id: pyupgrade
        name: Upgrade syntax for newer versions of the language (pyupgrade)
        args:
          - '--py37-plus'
  - repo: 'https://github.com/asottile/reorder_python_imports'
    tech_blogrev: v2.3.0
    hooks:
      - id: reorder-python-imports
        name: 'Reorder Python imports (src, tests)'
        files: ^(?!examples/)
        args:
          - '--application-directories'
          - app
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: 'https://github.com/psf/black'
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: 'https://github.com/asottile/dead'
    rev: v1.3.0
    hooks:
      - id: dead
