resolution: 1 # Resolution of the images in meters per pixel
n_imgs: 986 # it has to be the same else we can't stack images together 
sizes: [64]

squares:
  64x64:
    x_dim: 64
    y_dim: 64
    side_lens: [1, 1, 2, 3, 5, 8, 13]  # Up to (64//5)
    margin: 5
  32x32:
    x_dim: 32
    y_dim: 32
    side_lens: [1, 2, 3, 5]  # Up to (32//5)
    margin: 5
  16x16:
    x_dim: 16
    y_dim: 16
    side_lens: [1, 2, 3]  # Up to (16//5)
    margin: 3

trenches:
  difficulty_levels: ["easy", "medium", "hard"]
  trenches_per_level: [[1, 1], [2, 2], [3, 3]]
  trench_dims_min_ratio: [0.05, 0.1]  # Ratios for calculating min dimensions
  trench_dims_max_ratio: [0.15, 0.4]  # Ratios for calculating max dimensions
  img_edge_min: 64
  img_edge_max: 64
  # obstacles 
  n_obs_min: 1
  n_obs_max: 3
  size_obstacle_min: 2
  size_obstacle_max: 8
  # dumping constraints  
  n_nodump_min: 1
  n_nodump_max: 3
  size_nodump_min: 2
  size_nodump_max: 8


foundations:
  dataset_rel_path: "data/openstreet/"
  size: 64